<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5517da7b412ac03d3fd302bb77c659b6
{
    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'ZBateson\\MailMimeParser\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ZBateson\\MailMimeParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/zbateson/mail-mime-parser/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5517da7b412ac03d3fd302bb77c659b6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5517da7b412ac03d3fd302bb77c659b6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
