#!/bin/bash

####     Functions    ####
read_def (){
    # Use: read_def <prompt> <default>
    prompt="$1"
    default="$2"

    read -p "$prompt [$default]: " var
    test -z $var && var=$default

    echo "$var"
}

####     Install Prerequisites     ####
apt install -y rsyslog
apt install -y apache2 
apt install -y php7.2 libapache2-mod-php php-mysql php-mbstring php-xml

a2enmod php7.2

####     PHP        ####

## Set php.ini vals

echo '# PHP directives for AuroraML - Worker.
[Auroraml]
error_log = "syslog"
log_errors = On
error_reporting = E_ALL & ~E_STRICT
display_errors = Off

' > "$(ls -d /etc/php/7.*/apache2/conf.d | tail -n 1)/50-auroraml-worker.ini"


####     SYSLOG     ####

syslog_server=$(read_def "Syslog Remote Server" "192.168.0.10" )

# Local Config (Master must be set independently)
echo "# Messages generated by AuroraML code
if \$syslogtag == \"auroraml-worker:\" then @@${syslog_server}:514
& stop

# Messages generated by PHP
:msg,regex,\"^[w: ]*PHP \"    @@${syslog_server}:514
:msg,startswith,\"  [wrapped:\"   @@${syslog_server}:514
& stop

" > "/etc/rsyslog.d/40-auroraml-worker.conf"

####    Aurora    ####

aurora_etc_dir="/etc/auroraml"
test -d "$aurora_etc_dir" || ( mkdir "$aurora_etc_dir" && chmod 755 "$aurora_etc_dir" )

# Direcciones baneadas
echo '; Lista de direcciones filtradas
; banned[]="isabel@elpuent.com"
banned[]="#^mailer-daemon@.*$#is"
banned[]="#^nospam@.*$#is"
banned[]="#^.*@fcm\.pri\.sld\.cu$#is"
banned[]="#^.*@dmsch\.sld\.cu$#is"
banned[]="reina.meli@nauta.cu"
; Estafadores
banned[]="alexdjcom@nauta.cu"
banned[]="adrianojrbr@nauta.cu"
banned[]="winnie25@nauta.cu"
banned[]="igaki@nauta.cu"
banned[]="jobplay@nauta.cu"
banned[]="anyelinai@nauta.cu"
banned[]="anyitamayo@nauta.cu"
banned[]="yordan.almenares@nauta.cu"
banned[]="barrerasyaima@nauta.cu"
banned[]="puchi79@nauta.cu"
banned[]="loidmila@nauta.cu"
banned[]="aracelishidalgo@nauta.cu"
banned[]="reynier1505@nauta.cu"
banned[]="noel1010@nauta.cu"

; Comemierdas que reclamaron dinero

; Un tipo que no quiere recibir correos
banned[]="yadir87@nauta.cu"
' > "${aurora_etc_dir}/banned.ini"


# Configuracion de AuroraSuite


echo "<?php

// MYSQL
define('MYSQL_HOST', '$(read_def "Mysql Host" "192.168.0.11")');
define('MYSQL_PORT', $(read_def "Mysql Port" "3306"));
define('MYSQL_USER', '$(read_def "Mysql User" "")');
define('MYSQL_PASS', '$(read_def "Mysql Pass" "")');
define('MYSQL_DB', '$(read_def "Mysql Database" "")');


// SMTP
define('MAIL_IS_SMTP', 1);
define('SMTP_HOST', '$(read_def "SMTP Host" "192.168.0.10")');
define('SMTP_PORT', $(read_def "SMTP Port" "25"));
define('SMTP_AUTH', 0);
define('SMTP_SSL', 0);

define('SMTP_DEBUG', 0);


// Mail
define('MAIL_DOMAIN', 'auroraml.com');
define('MAIL_USER', 'w2m');
define('MAIL_NAME', 'Aurora Mail');
define('SERVICE_ADDRESS', 'w2m@auroraml.com');
define('SUPPORT_ADDRESS', 'nauta.fw@gmail.com');

// Misc
define('_DEBUG_', 0);
define('REPORT_ERRORS', 0);
//define('ERROR_REPORTING', 0);

define('DIAS_PRUEBA', 7);

// Version Minima de AuroraSuite para nuevos usuarios
define('AU_NEW_USER_MIN_VERSION_CODE ',  13);
define('AU_NEW_USER_MIN_VERSION_NAME ',  '6.0.1');

// Hack para cuando hay una cola enorme de entrada
// porque el sistema estuvo caido
define('DROP_ALL', 0);

// Other configurations
define('REV_BASE', 'http://www.revolico.com');

define('SERVICES_PATH', DOCUMENT_ROOT . DS . 'mail_services');
define('MOBILE_SERVICES_PATH', DOCUMENT_ROOT . DS .'mobile_services');
define('SMS_SERVICES_PATH', DOCUMENT_ROOT . DS .'sms_service');

" > "${aurora_etc_dir}/config.php"

# Importar la configuracion en AuroraSuite
echo "<?php
require_once '${aurora_etc_dir}/config.php';

define('AURORA_CONFIG_DIR', '${aurora_etc_dir}');
define('BANNED_FILE', '${aurora_etc_dir}/banned.ini');

" > "../config/config.php"

systemctl restart rsyslog
systemctl restart apache2

