#!/bin/bash

apt install -y rsyslog

syslog_server=$( read_def "Syslog Remote Server" "192.168.0.10" )

# Local Config (Master must be set independently)
echo "# Messages generated by AuroraML code
if \$syslogtag == \"auroraml-worker:\" then @@${syslog_server}:514
& stop

# Messages generated by PHP
:msg,regex,\"^[w: ]*PHP \"    @@${syslog_server}:514
:msg,startswith,\"  [wrapped:\"   @@${syslog_server}:514
& stop

" > "/etc/rsyslog.d/40-auroraml-worker.conf"

systemctl restart rsyslog
